### ISSUE TITLE
code sparse version in the future

### ISSUE THREAD

**Issue by hugoguh** [glm-tools/pyglmnet#41] opened 2016-05-05 15:44 UTC
blows up my memory, and sklearn doesn’t on the same dataset. 
Useful for problems with categorical features, number of features increases a lot with onehotencoder, but X will be sparse.

**Comment by jasmainak** [comment] 2016-05-06 00:27
Memory profiling might be a good idea to see what's the culprit: http://fa.bianp.net/blog/2012/line-by-line-report-of-memory-usage/

**Comment by pavanramkumar** [comment] 2018-08-27 00:05
duplicate of #229

**Closed by pavanramkumar** 2018-08-27 00:05 UTC
Labels: enhancement
