### ISSUE TITLE
Add negative binomial link function

### ISSUE THREAD

**Issue by themantalope** [glm-tools/pyglmnet#163] opened 2016-10-12 21:45 UTC
Just putting this up as a potential enhancement.

**Comment by pavanramkumar** [comment] 2016-11-17 20:15
there are four different variants of Poisson regression -- all for count distributions:

- Quasi-Poisson (which allows variance to be proportional rather than equal to the mean)
- Zero-inflated Poisson (to allow for more zeros than account for by a Poisson distribution)
- Zero-truncated and hurdle models (another way to deal with more than expected zero observations)
- Negative binomial

All methods are implemented in R but in different packages. This [paper](http://www.jstatsoft.org/v27/i08/paper) and corresponding [code examples](http://data.princeton.edu/wws509/r/overdispersion.html) give you a sense of the applications.

**Comment by themantalope** [comment] 2016-11-17 21:33
Thanks! I'll start taking a look.

**Comment by geektoni** [comment] 2018-12-05 10:45
Hi there! I'm reviving this issue because I wanted to know if this feature is planned to be released in the future (or, better, if somebody is currently developing it) or not. I am currently working on a project which requires it and it would be really nice to know that it will be available in your framework :)

**Comment by jasmainak** [comment] 2018-12-05 23:23
@geektoni which of the link functions are you most interested in? Unfortunately, I'm crazy busy these days. However, I am happy to guide and review a pull request if someone has the motivation to implement it :)

**Comment by geektoni** [comment] 2018-12-06 13:30
@jasmainak I was interested in the Negative Binomial. If nobody is working on it at the moment I think I'll give it a try to add it as a new noise model. This is not quite my field, but let's see what happens. Apart from the paper and code examples outlined above, are there any other suggested references I should know before starting designing/implementing it? :)

**Comment by jasmainak** [comment] 2018-12-06 21:52
not me, @pavanramkumar is the expert on GLMs. Maybe he can suggest something :)

What I would suggest is to first write down the equations in the [cheatsheet](http://glm-tools.github.io/pyglmnet/cheatsheet.html). Once you have the log likelihood and the gradients, it should be straightforward to plug them into `pyglmnet`. You can first update the tests for the gradients and then write code to make the tests pass. Do not hesitate to let us know if you get stuck.

**Comment by pavanramkumar** [comment] 2018-12-06 22:03
@geektoni thanks for taking a stab at it! what @jasmainak suggests is probably the right approach: deriving the log likelihood and writing the gradient tests would be a start. 

the paper linked above is a starting point but i'll add any other references that may be appropriate. 

to clarify: i hope you're looking at neg-binomial with a fixed shape parameter -- this is a special case of a GLM, and can likely be implemented in the same `GLM()` class. 

however, if you want to estimate both mean and shape parameters, you would have to take an iterative approach: estimating mean for a fixed shape, then shape for a fixed mean, and so on until convergence. for this more general case, i would recommend a different class.

**Comment by geektoni** [comment] 2019-01-03 22:20
@pavanramkumar Yes, I am just interested in fixed shape negative binomial (the more complex case could happen later on). Regarding the implementation, I have a few questions: 
- Should I use the classical log-link function or are there "better" ones (maybe because of numerical stability problems etc.)?
- Do I need to include just the L2-regularization inside the loss function or can I plug in directly the elastic net formulation? I saw that in your cheatsheet the loss functions use only L2-regularization (I have still to check the source code more thoroughly, so I may answer myself in the next few days). 

P.S: the gradients/Hessians/log-likelihood I am currently using are [here](https://github.com/glm-tools/pyglmnet/files/2725460/NB_GLM_cheatsheet.pdf).

**Comment by jasmainak** [comment] 2019-01-04 17:57
@geektoni I will answer point 2 -- maybe @pavanramkumar can shed some light on point 1.

You need to add your log-likelihood (without the regularization term -- i.e., no L2) [here](https://github.com/glm-tools/pyglmnet/blob/master/pyglmnet/pyglmnet.py#L114). The loss will be computed from this. Then you have to update [this](https://github.com/glm-tools/pyglmnet/blob/master/pyglmnet/pyglmnet.py#L208) and [this](https://github.com/glm-tools/pyglmnet/blob/master/pyglmnet/pyglmnet.py#L255).

Feel free to make a WIP (work in progress) PR so we can help early on rather than wait to have perfect code ...

**Comment by geektoni** [comment] 2019-01-04 18:01
> @geektoni I will answer point 2 -- maybe @pavanramkumar can shed some light on point 1.
> 
> You need to add your log-likelihood (without the regularization term -- i.e., no L2) [here](https://github.com/glm-tools/pyglmnet/blob/master/pyglmnet/pyglmnet.py#L114). The loss will be computed from this. Then you have to update [this](https://github.com/glm-tools/pyglmnet/blob/master/pyglmnet/pyglmnet.py#L208) and [this](https://github.com/glm-tools/pyglmnet/blob/master/pyglmnet/pyglmnet.py#L255) for the gradient and hessian respectively.
> 
> Feel free to make a WIP (work in progress) PR so we can help early on rather than wait to have perfect code ...

Ok, that makes sense. I'll try to push something in the next days so you can have a look at it.

**Closed** 2020-08-16 16:40 UTC
Labels: enhancement
