### ISSUE TITLE
_prox function returns nan when a group of beta parameters are set to zero

### ISSUE THREAD

**Issue by themantalope** [glm-tools/pyglmnet#170] opened 2016-10-28 19:53 UTC
Currently, the update part of the`_prox` function is implemented as follows for the the case of group lasso:

```
group_ids = np.unique(self.group)
            group_norms = np.abs(beta)

            for group_id in group_ids:
                if group_id != 0 and not np.all(beta[self.group == group_id] == 0.0):
                    group_norms[self.group == group_id] = \
                        np.linalg.norm(beta[self.group == group_id], 2)

return ( beta - thresh * beta / group_norms) * (group_norms > thresh)
```

If a group of betas are zero (or very close to zero) then the l2 norm will be zero, resulting in `nan`s in the `beta` array. I've fixed this by indexing updating on the nonzero indicies of beta.

**Comment by tristanstoeber** [comment] 2017-02-14 21:25
My problem seems related to the closed bug report. I am using pyglmnet '1.0.1'
My design matrix has floats and no NaNs, same for my y (which is spikes, so 0. and 1.) . But when I do the fit, both beta and beta0 are only nans.

`glm_poissonexp = pyglm.GLM(distr='poisson', verbose=True, alpha=1., group=groups, solver='cdfast')`

groups looks like [0.,0., ..., 1., 1.,1.].

Any idea where the bug may be?

**Comment by jasmainak** [comment] 2017-02-14 22:24
okay I see. PR is welcome. If you don't have time to submit a PR, can you share a small script to reproduce?

**Comment by pavanramkumar** [comment] 2017-02-14 22:35
thanks @tristanstoeber i've reopened the issue. i suspect the fixing PR only tested it for the `batch-gradient` solver. i'll check soon.

**Comment by pavanramkumar** [comment] 2017-03-27 22:43
hey @tristanstoeber we're working this week to exclusively improve unfixed issues for pyglmnet. i've tried to reproduce your group lasso issue with a sparse simulated dataset, but I haven't experienced any `NaN` issues.

you can try running it like so:

```
import numpy as np
from pyglmnet import GLM
import scipy.sparse as sps

n_samples = 1000
n_features = 100
X = np.random.randn(n_samples, n_features)

beta0 = np.random.rand()
density = 0.5
beta = sps.rand(n_features, 1, density=density).toarray()[:, 0]

glm_sim = GLM(distr='poisson')
y = glm_sim.simulate(beta0, beta, X)

groups = np.concatenate((np.ones(n_features/2), 2 * np.ones(n_features/2)))

glm = GLM(distr='poisson', verbose=True, alpha=0.1, group=groups, solver='batch-gradient')
glm.fit(X, y)
```
a couple of further comments about your code above:

- note that group IDs start from `(1, ..., n_groups)`. if a particular parameter's group ID is `0`, we treat it as subject to a regular L1, not a group lasso penalty.

- the potential division by zero due to `hk --> 0` is not unique to group lasso. it would be great if you can test this on the same dataset without a group lasso constraint. 

you're welcome to collaborate on a PR to solve this issue. cheers!

**Comment by tristanstoeber** [comment] 2017-03-28 07:34
Hey Pavan,

thanks for looking into this. Your code snippet runs without error on my machine and the output is:
Looping through the regularization path
Lambda: 0.5000
	Converged. Loss function: -20.23
	dL/L: 0.000098

Lambda: 0.3237
	Converged. Loss function: -20.70
	dL/L: 0.000600

Lambda: 0.2096
	Converged. Loss function: -21.08
	dL/L: 0.000881

Lambda: 0.1357
	Converged. Loss function: -21.38
	dL/L: 0.000900

Lambda: 0.0879
	Converged. Loss function: -21.61
	dL/L: 0.000808

Lambda: 0.0569
	Converged. Loss function: -21.79
	dL/L: 0.000681

Lambda: 0.0368
	Converged. Loss function: -21.92
	dL/L: 0.000552

Lambda: 0.0239
	Converged. Loss function: -22.01
	dL/L: 0.000437

Lambda: 0.0154
	Converged. Loss function: -22.08
	dL/L: 0.000339

Lambda: 0.0100
	Converged. Loss function: -22.13
	dL/L: 0.000261

Out[1]: 
<
Distribution | poisson
alpha | 0.10
max_iter | 1000.00
lambda: 0.50 to 0.01
>

I will spend some time later today or tomorrow to create a minimal example to reproduce my problem.
Best,
Tristan

**Comment by pavanramkumar** [comment] 2017-03-29 19:52
ok @tristanstoeber, keep us posted! we have two more days. gonna be hard to have the same level of focus after this week.

**Comment by pavanramkumar** [comment] 2017-08-27 16:37
closing this since issue was not reproducible

**Closed by pavanramkumar** 2017-08-27 16:37 UTC
Labels: bug
